// Copyright 2021, pdfium-sys Developers
// Copyright 2022 - 2024, pdfium-render Developers
//
// Licensed under the Apache License, Version 2.0, <LICENSE-APACHE or
// http://apache.org/licenses/LICENSE-2.0> or the MIT license <LICENSE-MIT or
// http://opensource.org/licenses/MIT>, at your option. This file may not be
// copied, modified, or distributed except according to those terms.

#[cfg(feature = "bindings")]
extern crate bindgen;

#[cfg(feature = "bindings")]
use {
    bindgen::BindgenError,
    std::env::var,
    std::ffi::OsStr,
    std::fs::{read_dir, write},
    std::path::PathBuf,
};

#[derive(Debug)]
enum BuildError {
    #[cfg(feature = "bindings")]
    #[allow(dead_code)]
    IoError(std::io::Error),
    #[cfg(feature = "bindings")]
    #[allow(dead_code)]
    BindgenError(BindgenError),
    #[cfg(feature = "bindings")]
    #[allow(dead_code)]
    PathConversionError(PathBuf),
}

#[cfg(feature = "bindings")]
impl From<std::io::Error> for BuildError {
    fn from(item: std::io::Error) -> Self {
        BuildError::IoError(item)
    }
}

#[cfg(feature = "bindings")]
impl From<BindgenError> for BuildError {
    fn from(item: BindgenError) -> Self {
        BuildError::BindgenError(item)
    }
}

fn main() -> Result<(), BuildError> {
    #[cfg(feature = "bindings")]
    build_bindings()?;

    #[cfg(feature = "static")]
    statically_link_pdfium();

    Ok(())
}

#[cfg(feature = "bindings")]
fn build_bindings() -> Result<(), BuildError> {
    // AJRC - 3-Jan-22 - modified from the pdfium-sys version to removing explicit linking to
    // a system-provided pdfium. We still want the bindings generated by rust-bindgen,
    // since they provide various constants that are useful, but we will load functions
    // dynamically at runtime using libloading.

    // AJRC - 13-Jan-22 - docs.rs runs cargo doc in a read-only sandbox, so we can't
    // generate bindings. Skip bindings generation entirely if the DOCS_RS environment
    // variable is set, as per https://docs.rs/about/builds#detecting-docsrs.

    // AJRC - 22-Jan-22 - expanded bindings generation to cover all Pdfium modules, not
    // just the viewing and rendering functionality defined in fpdfview.h.

    // AJRC - 5-Aug-24 - expanded bindings generation to cover multiple versions of the Pdfium API.
    // Consumers can use crate feature flags to select a specific API version to use.

    for release in read_dir("include/")? {
        let release = release?.path();

        if release.is_dir() {
            build_bindings_for_one_pdfium_release(
                release
                    .file_name()
                    .ok_or(BuildError::PathConversionError(release.clone()))?
                    .to_str()
                    .ok_or(BuildError::PathConversionError(release.clone()))?,
            )?;
        }
    }

    Ok(())
}

#[cfg(feature = "bindings")]
fn build_bindings_for_one_pdfium_release(release: &str) -> Result<(), BuildError> {
    if var("DOCS_RS").is_err() {
        // The DOCS_RS environment variable is _not_ set. Proceed with bindgen.

        // Generate an import wrapper telling bindgen which header files to use as input sources.

        let header_file_extension = OsStr::new("h");
        let wrapper_file_name = OsStr::new("rust-import-wrapper.h");
        let mut included_header_files = Vec::new();

        for header in read_dir(format!("include/{}/", release))? {
            let header = header?.path();

            if header.is_file()
                && header.file_name().is_some()
                && header.extension() == Some(header_file_extension)
                && header.file_name() != Some(wrapper_file_name)
            {
                // Include this header file in the list of input sources.

                let header_file_name = header
                    .file_name()
                    .ok_or(BuildError::PathConversionError(header.clone()))?
                    .to_str()
                    .ok_or(BuildError::PathConversionError(header.clone()))?
                    .to_owned();

                included_header_files.push(header_file_name);
            }
        }

        let wrapper = included_header_files
            .iter()
            .map(|file_name| format!("#include \"{}\"", file_name))
            .collect::<Vec<_>>()
            .join("\n");

        write(
            format!("include/{}/rust-import-wrapper.h", release),
            wrapper,
        )?;

        let bindings = bindgen::Builder::default()
            // The input header we would like to generate bindings for.
            .header(format!("include/{}/rust-import-wrapper.h", release))
            .clang_arg("-DPDF_USE_SKIA") // Also generate bindings for optional SKIA functions
            .clang_arg("-D_SKIA_SUPPORT_") // (Alternative name for this setting in Pdfium 5961 and earlier)
            .clang_arg("-DPDF_ENABLE_XFA") // Also generate bindings for optional XFA functions
            .clang_arg("-DPDF_ENABLE_V8") // Also generate bindings for optional V8 functions
            .generate_cstr(true) // Recommended for Rust 1.59 and later
            .enable_function_attribute_detection()
            .size_t_is_usize(true) // There are esoteric architectures where size_t != usize. See:
            // https://github.com/rust-lang/rust-bindgen/issues/1671
            // Long term, the solution is for Bindgen to switch to converting size_t to
            // std::os::raw::c_size_t instead of usize, but c_size_t is not yet stabilized.
            .layout_tests(false) // bindgen 0.71.1 outputs FPDF_BSTR size checks
            // that break WASM builds when this flag is enabled
            .parse_callbacks(Box::new(bindgen::CargoCallbacks::new())) // Tell cargo to invalidate
            // the built crate whenever any of the included header files change.
            .clang_args(
                // Try to keep original C++ comments for docs.
                [
                    "-fretain-comments-from-system-headers",
                    "-fparse-all-comments",
                ]
                .iter(),
            )
            .generate_comments(true);

        #[cfg(feature = "pdfium_use_win32")]
        let bindings = bindings.clang_arg("-D_WIN32"); // Also generate bindings for Windows-specific functions

        // Generate the bindings to src/bindgen.rs.

        let bindings = bindings.generate()?;
        let out_path = PathBuf::from("src");

        bindings.write_to_file(out_path.join(format!("bindgen/{}.rs", release)))?;
    }

    Ok(())
}

/// Where the PDFium static library is — PRODUCING it first when it is not
/// already in the build directory.
///
/// PDFium is a build product and is never committed. The recipe that produces
/// it lives in its own repository (`pdfium-bundle.txt` pins which revision), so
/// this clones that repository into the build directory and runs it, exactly as
/// the ffmpeg bundle builds its own archives. A consumer resolving this crate
/// from a git tag therefore needs no manual step and no prebuilt binary.
///
/// It used to GUESS instead: `current_dir()/dist/lib`, the directory the
/// consumer happened to be invoked from — not this crate's, and not anywhere
/// the library would be. Being wrong there produced no message at all: the
/// search path matched nothing and the failure arrived much later as an
/// unresolved-symbol link error naming PDFium internals.
///
/// Be warned that the first build is genuinely large — Chromium's toolchain, a
/// full source sync, tens of gigabytes of scratch and hours of compilation. It
/// is cached by build identity afterwards, so it happens once per recipe
/// revision and platform.
#[cfg(feature = "static")]
fn bundled_lib_path() -> String {
    use std::path::PathBuf;

    println!("cargo:rerun-if-env-changed=PDFIUM_BUNDLE_DIST_DIR");
    println!("cargo:rerun-if-env-changed=PDFIUM_STATIC_LIB_PATH");
    println!("cargo:rerun-if-changed=pdfium-bundle.txt");

    // An outright override: "I already have one, here it is, build nothing."
    // Honoured first and taken at its word — the point of naming a directory is
    // to be believed about it.
    if let Ok(path) = std::env::var("PDFIUM_STATIC_LIB_PATH") {
        if !path.trim().is_empty() {
            return path;
        }
    }

    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let (repo, tag) = pinned_recipe(&manifest_dir);
    let identity = pdfium_build_identity(&repo, &tag);

    // `PDFIUM_BUNDLE_DIST_DIR` names WHERE the library goes, not merely where
    // it might already be — so pointing it at an empty directory builds into
    // it rather than failing. `OUT_DIR` is the default, and is cargo's own
    // build directory; the override exists because it differs per target
    // directory and this is far too expensive to repeat per tree.
    let dist = match std::env::var("PDFIUM_BUNDLE_DIST_DIR") {
        Ok(dir) if !dir.trim().is_empty() => PathBuf::from(dir),
        _ => PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets OUT_DIR"))
            .join(format!("pdfium-dist-{identity}")),
    };
    let archive = dist.join("lib").join(static_library_name());
    if archive.is_file() && recipe_matches(&dist, &identity) {
        println!("cargo:rerun-if-changed={}", archive.to_string_lossy());
        return dist.join("lib").to_string_lossy().into_owned();
    }

    build_pdfium(&repo, &tag, &identity, &dist);

    if !archive.is_file() {
        panic!(
            "pdfium-render-bundled: {archive:?} is missing after a successful run of the \n\
             recipe at {repo} {tag}. The recipe and this crate disagree about what it \n\
             produces."
        );
    }
    println!("cargo:rerun-if-changed={}", archive.to_string_lossy());
    dist.join("lib").to_string_lossy().into_owned()
}

/// What the recipe calls the static library on this platform.
///
/// The recipe produces `pdfium.lib` under MSVC and `libpdfium.a` everywhere
/// else, and says so at the top of `build.ps1`: "MSVC emits .obj (not .o); the
/// archiver is lib.exe (not ar); the static link name is pdfium.lib (not
/// libpdfium.a)."
///
/// This crate looked for `libpdfium.a` on every platform, so on Windows the
/// recipe ran for the better part of an hour, succeeded, published
/// `dist\lib\pdfium.lib`, and the build script then panicked with
///
///     "...\dist\lib\libpdfium.a" is missing after a successful run of the
///     recipe. The recipe and this crate disagree about what it produces.
///
/// which is exactly what had happened. Derived from the TARGET rather than the
/// host: a build script runs on the host and this name belongs to the thing
/// being built.
#[cfg(feature = "static")]
fn static_library_name() -> &'static str {
    // `CARGO_CFG_TARGET_ENV` is `msvc` for `*-pc-windows-msvc` and `gnu` for
    // the MinGW targets, which do use the POSIX name.
    match std::env::var("CARGO_CFG_TARGET_ENV").as_deref() {
        Ok("msvc") => "pdfium.lib",
        _ => "libpdfium.a",
    }
}

/// The pinned recipe: which repository, at which tag.
#[cfg(feature = "static")]
fn pinned_recipe(manifest_dir: &std::path::Path) -> (String, String) {
    let path = manifest_dir.join("pdfium-bundle.txt");
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("pdfium-render-bundled: cannot read {path:?}: {e}"));
    let mut repo = String::new();
    let mut tag = String::new();
    for line in raw.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        match line.split_once('=') {
            Some((key, value)) => match key.trim() {
                "repo" => repo = value.trim().to_string(),
                "tag" => tag = value.trim().to_string(),
                other => panic!("pdfium-render-bundled: {path:?} names unknown key '{other}'"),
            },
            None => panic!("pdfium-render-bundled: {path:?} line '{line}' is not key = value"),
        }
    }
    if repo.is_empty() || tag.is_empty() {
        panic!(
            "pdfium-render-bundled: {path:?} must pin both `repo` and `tag` — an unpinned \n\
             recipe would produce a different library on different days."
        );
    }
    (repo, tag)
}

/// What the built library depends on: the recipe revision, and the platform.
#[cfg(feature = "static")]
fn pdfium_build_identity(repo: &str, tag: &str) -> String {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};
    let mut hasher = DefaultHasher::new();
    repo.hash(&mut hasher);
    tag.hash(&mut hasher);
    std::env::var("TARGET").unwrap_or_default().hash(&mut hasher);
    format!("{:016x}", hasher.finish())
}

/// Whether a built tree was produced by THIS recipe revision.
///
/// A stamp beside the library, not an assumption. Reusing a library built from
/// a different recipe is how a consumer links against something nobody asked
/// for — and at this build's cost, nobody would rebuild to find out.
#[cfg(feature = "static")]
fn recipe_matches(dist: &std::path::Path, identity: &str) -> bool {
    std::fs::read_to_string(dist.join(".pdfium-build-id"))
        .map(|stamp| stamp.trim() == identity)
        .unwrap_or(false)
}

/// Whether the process that wrote `owner` is still running.
///
/// A lock directory on its own says somebody once started a build; it cannot
/// say whether they are still at it. The pid inside can: `kill(pid, 0)` asks
/// the kernel, which is the only party that knows.
///
/// Answers TRUE when it cannot tell — an unreadable or malformed file, a pid
/// this process may not signal. A waiter that guesses "gone" and guesses wrong
/// starts a second builder against the first, which is hours of work done
/// twice and two writers in one output directory. Waiting needlessly costs
/// time; taking over wrongly costs correctness.
///
/// A missing file is the one unambiguous answer: locks written before this
/// have none, and neither does a directory left by a kill between `create_dir`
/// and the write.
#[cfg(feature = "static")]
fn lock_owner_is_alive(owner: &std::path::Path) -> bool {
    let Ok(text) = std::fs::read_to_string(owner) else {
        return false;
    };
    let Ok(pid) = text.trim().parse::<i32>() else {
        return true;
    };
    if pid <= 0 {
        return true;
    }
    // Signal 0 performs the permission and existence checks and sends nothing.
    // ESRCH — and only ESRCH — means no such process; EPERM means it is there
    // and belongs to somebody else.
    let alive = unsafe { libc_kill(pid, 0) } == 0
        || std::io::Error::last_os_error().raw_os_error() != Some(3);
    alive
}

// `kill(2)`, declared here rather than taken from a crate: a build script's
// dependencies are built before every build that uses it, and this needs one
// symbol.
#[cfg(feature = "static")]
extern "C" {
    #[link_name = "kill"]
    fn libc_kill(pid: i32, sig: i32) -> i32;
}

/// Clone the pinned recipe into the build directory and run it.
#[cfg(feature = "static")]
fn build_pdfium(repo: &str, tag: &str, identity: &str, dist: &std::path::Path) {
    use std::path::PathBuf;

    let build_root = dist
        .parent()
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."));
    let recipe = build_root.join(format!("pdfium-bundle-{tag}"));

    // One builder at a time. This is the most expensive thing in the workspace;
    // two cargo invocations doing it at once would be hours wasted twice.
    //
    // The lock names its OWNER. A directory on its own says only that somebody
    // once started a build, and a build that was killed — ^C, a test runner
    // stopped, a machine rebooted — leaves one that no longer means anything.
    // The next build then waited the full six hours for a process that did not
    // exist, at nought per cent CPU, which reads as a hung test rather than as
    // a wait: `cargo test` sat for forty-eight minutes on a lock whose owner
    // had been killed three hours earlier.
    //
    // So the pid goes inside, and a waiter that finds the owner gone takes over
    // at once. Only the OWNER's absence releases it: a live builder still holds
    // it for as long as it runs, however long that is, which is the whole point
    // of the lock.
    let lock = build_root.join(format!("pdfium-lock-{identity}"));
    let owner = lock.join("owner.pid");
    let _ = std::fs::create_dir_all(&build_root);
    let mut held = std::fs::create_dir(&lock).is_ok();
    if held {
        let _ = std::fs::write(&owner, std::process::id().to_string());
    } else if !lock_owner_is_alive(&owner) {
        // Nobody is building. Take it over now rather than in six hours.
        println!(
            "cargo:warning=pdfium-render-bundled: taking over an abandoned build \
             lock at {lock:?} (its owner is gone)"
        );
        let _ = std::fs::remove_dir_all(&lock);
        held = std::fs::create_dir(&lock).is_ok();
        if held {
            let _ = std::fs::write(&owner, std::process::id().to_string());
        }
    }
    if !held {
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(6 * 60 * 60);
        while std::time::Instant::now() < deadline {
            if dist.join("lib").join(static_library_name()).is_file()
                && recipe_matches(dist, identity)
            {
                return;
            }
            // Re-checked every time round, not once before the loop: the owner
            // can die while this waits, and waiting on a dead one is the bug
            // this whole arrangement exists to avoid.
            if !lock_owner_is_alive(&owner) {
                println!(
                    "cargo:warning=pdfium-render-bundled: the build holding \
                     {lock:?} went away; taking over"
                );
                break;
            }
            std::thread::sleep(std::time::Duration::from_secs(10));
        }
        let _ = std::fs::remove_dir_all(&lock);
        let _ = std::fs::create_dir(&lock);
        let _ = std::fs::write(&owner, std::process::id().to_string());
    }

    let result = run_pdfium_recipe(repo, tag, &recipe, dist);
    if result.is_ok() {
        let _ = std::fs::write(dist.join(".pdfium-build-id"), identity);
    }
    let _ = std::fs::remove_dir(&lock);
    if let Err(message) = result {
        panic!("{message}");
    }
}

#[cfg(feature = "static")]
fn run_pdfium_recipe(
    repo: &str,
    tag: &str,
    recipe: &std::path::Path,
    dist: &std::path::Path,
) -> Result<(), String> {
    if !recipe.join("build.sh").is_file() {
        let _ = std::fs::remove_dir_all(recipe);
        println!("cargo:warning=pdfium-render-bundled: cloning {repo} at {tag}");
        let status = std::process::Command::new("git")
            .args(["clone", "--depth", "1", "--branch", tag, repo])
            .arg(recipe)
            .status()
            .map_err(|e| format!("pdfium-render-bundled: cannot run git to clone {repo}: {e}"))?;
        if !status.success() {
            return Err(format!(
                "pdfium-render-bundled: cloning {repo} at {tag} failed ({status})."
            ));
        }
    }

    println!(
        "cargo:warning=pdfium-render-bundled: building PDFium into {dist:?}. This is \
         Chromium's build system — tens of gigabytes of scratch and hours of compilation, \
         once per recipe revision and platform."
    );
    let script = if cfg!(windows) { "build.ps1" } else { "build.sh" };
    let mut command = if cfg!(windows) {
        let mut c = std::process::Command::new("powershell");
        c.args(["-NoProfile", "-ExecutionPolicy", "Bypass", "-File"]);
        c.arg(recipe.join(script));
        c
    } else {
        let mut c = std::process::Command::new("bash");
        c.arg(recipe.join(script));
        c
    };
    let status = command
        .current_dir(recipe)
        .env("PDFIUM_BUNDLE_DIST_DIR", dist)
        .status()
        .map_err(|e| format!("pdfium-render-bundled: cannot run {script}: {e}"))?;
    if !status.success() {
        return Err(format!(
            "pdfium-render-bundled: {script} from {repo} {tag} failed ({status}).\n\
             It needs git, python3, ninja and a working C++ toolchain, and fetches \
             Chromium's depot_tools."
        ));
    }
    Ok(())
}

#[cfg(feature = "static")]
fn statically_link_pdfium() {
    let bundled_lib_path = bundled_lib_path();

    println!("cargo:rustc-link-lib=static=pdfium");
    println!("cargo:rustc-link-search=native={}", bundled_lib_path);
    
    // Required system frameworks on macOS
    #[cfg(target_os = "macos")]
    {
        println!("cargo:rustc-link-lib=framework=ApplicationServices");
        println!("cargo:rustc-link-lib=framework=CoreFoundation");
        println!("cargo:rustc-link-lib=framework=CoreText");
        println!("cargo:rustc-link-lib=framework=Foundation");
        println!("cargo:rustc-link-lib=framework=Security");
    }
    
    // Windows: MSVC links the CRT and C++ runtime automatically. PDFium and
    // Chromium's base/partition_alloc reference a set of Win32 system import
    // libraries (GDI text backend, timeGetTime from winmm, Uniscribe, etc.).
    // If linking surfaces more unresolved externals, add the named libs here.
    #[cfg(target_os = "windows")]
    {
        for lib in [
            "gdi32", "user32", "advapi32", "winmm", "ole32", "oleaut32",
            "shell32", "shlwapi", "version", "usp10",
        ] {
            println!("cargo:rustc-link-lib=dylib={}", lib);
        }
    }

    // C++ standard library linking
    #[cfg(feature = "libstdc++")]
    println!("cargo:rustc-link-lib=dylib=stdc++");

    #[cfg(feature = "libc++")]
    println!("cargo:rustc-link-lib=dylib=c++");

    #[cfg(feature = "core_graphics")]
    println!("cargo:rustc-link-lib=framework=CoreGraphics");
    
    // A dynamic PDFium instead, when one is named. Mutually exclusive with the
    // static path resolved above, which is why it is the only branch left here.
    if let Ok(path) = std::env::var("PDFIUM_DYNAMIC_LIB_PATH") {
        println!("cargo:rerun-if-env-changed=PDFIUM_DYNAMIC_LIB_PATH");
        println!("cargo:rustc-link-lib=dylib=pdfium");
        println!("cargo:rustc-link-search=native={}", path);
    }
}
