[build-dependencies.bindgen]
optional = true
version = "0"

[dependencies]
bitflags = "2"
bytemuck = "1"
bytes = "1"
chrono = "0"
itertools = "0"
log = "0"
maybe-owned = "0"
once_cell = "1"
utf16string = "0"
vecmath = "1"

[dependencies.image_023]
default-features = false
features = ["jpeg"]
optional = true
package = "image"
version = "0.23"

[dependencies.image_024]
default-features = false
features = ["jpeg"]
optional = true
package = "image"
version = "0.24"

[dependencies.image_025]
default-features = false
features = ["jpeg"]
optional = true
package = "image"
version = "0.25"

[dev-dependencies]
axum = "0"
rand = "0"
rayon = "1"
tower = "0"

[dev-dependencies.tokio]
features = ["full"]
version = "1"

[features]
bindings = ["dep:bindgen"]
core_graphics = ["static"]
default = ["static", "libc++", "pdfium_latest", "thread_safe", "image"]
flatten = []
image = ["image_latest"]
image_023 = ["dep:image_023", "image_api"]
image_024 = ["dep:image_024", "image_api"]
image_025 = ["dep:image_025", "image_api"]
image_api = []
image_latest = ["image_025"]
"libc++" = ["static"]
"libstdc++" = ["static"]
paragraph = []
pdfium_5961 = []
pdfium_6015 = []
pdfium_6043 = []
pdfium_6084 = []
pdfium_6110 = []
pdfium_6124 = []
pdfium_6164 = []
pdfium_6259 = []
pdfium_6295 = []
pdfium_6337 = []
pdfium_6406 = []
pdfium_6490 = []
pdfium_6555 = []
pdfium_6569 = []
pdfium_6611 = []
pdfium_6666 = []
pdfium_6721 = []
pdfium_6996 = []
pdfium_7123 = []
pdfium_7215 = []
pdfium_7350 = []
pdfium_enable_v8 = []
pdfium_enable_xfa = []
pdfium_future = ["pdfium_use_skia", "pdfium_enable_xfa", "pdfium_enable_v8"]
pdfium_latest = ["pdfium_7350"]
pdfium_use_skia = []
pdfium_use_win32 = ["dep:windows"]
static = []
sync = ["thread_safe"]
thread_safe = []

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
doctest = false
name = "pdfium_render"

[package]
authors = ["Alastair Carey <alastair@alastaircarey.com>"]
categories = ["api-bindings", "multimedia::images", "visualization", "wasm"]
description = "A high-level idiomatic Rust wrapper around Pdfium, the C++ PDF library used by the Google Chromium project."
edition = "2021"
exclude = ["test/*.pdf"]
homepage = "https://github.com/ajrcarey/pdfium-render"
keywords = ["pdf", "pdfium"]
license = "MIT OR Apache-2.0"
name = "pdfium-render-bundled"
publish = true
readme = "README.md"
repository = "https://github.com/ajrcarey/pdfium-render"
rust-version = "1.61"
version = "1.464.4193"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libloading = "0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0"
console_log = "1"
js-sys = "0"
wasm-bindgen-futures = "0"

[target.'cfg(target_arch = "wasm32")'.dependencies.wasm-bindgen]
features = ["enable-interning"]
version = "0"

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
features = ["TextDecoder", "ImageData", "Window", "Response", "Blob"]
version = "0"

[target.'cfg(target_os = "windows")'.dependencies.windows]
optional = true
version = "0"
